[profile.default]
libs = ["lib"]
out = "out"
src = "src"

remappings = [
  '@/src=src',
  '@/script=script',
  '@/tests=tests',
  '@chainlink/contracts=lib/chainlink/contracts',
  '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
